# Generated by Django 5.1.5 on 2025-01-31 22:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('Img_name', models.CharField(max_length=100)),
                ('Image', models.ImageField(upload_to='pictures/')),
                ('shape', models.CharField(max_length=50)),
                ('x_cor', models.CharField(max_length=50)),
                ('y_cor', models.CharField(max_length=50)),
                ('z_cor', models.CharField(max_length=50)),
                ('Prefillcolor', models.CharField(choices=[('red', 'Elv: 0-1500 mm'), ('blue', 'Elv: 1500-3000 mm'), ('yellow', 'Elv: 3000-4500 mm'), ('brown', 'Elv: 4500-6000 mm'), ('green', 'Elv: 6000-7500 mm'), ('orange', 'Elv: 7500-9000 mm')], default='red', max_length=50)),
                ('Date', models.DateField()),
            ],
        ),
    ]
